version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started

  migrate:
    build: .
    environment:
      - DATABASE_URL=postgresql://akeron:hrpassword@postgres:5432/hr_assistant
    depends_on:
      postgres:
        condition: service_healthy
    command: ["npx", "prisma", "migrate", "deploy"]

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=hrpassword
      - POSTGRES_DB=hr_assistant
      - POSTGRES_USER=akeron
    ports:
      - "5432:5432"
    volumes:
      - hr_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U akeron -d hr_assistant"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  hr_postgres_data: